### ISSUE TITLE
Why was slim removed?

### ISSUE THREAD

**Issue by jacobg** [timbru31/docker-java-node#523]
Hi, wondering why 11-slim was removed?
https://github.com/timbru31/docker-java-node/commit/beeed48d87506e86f45412ba01e02f3e92505f36#diff-adb76474a4d21f08634f1141bb92786577a2cca214bc43ea65ebff9b578ea2e2

What is the closest upgrade path from 11-slim?

Thanks.

**Comment by timbru31** [comment]
Hello Jacob,

thanks for asking. The aim of my docker images is to provide the smallest file size possible, while installing a well known OpenJDK "variant"x. If I recall correctly, sometimes the OpenJDK images were a bit behind the official Oracle ones. Additionally, I've migrated my images to offer as many different architecture as possible, but OpenJDK only offered armv8/arm64 and amd64, while AdoptOpenJDK offers more. That's why I've decided to replace OpenJDK with AdaptOpenJDK. 

While migrating, it turned out, that the slim variant is quite obsolete with AdaptOpenJDK based images. Compare, e.g., these two tags https://hub.docker.com/layers/openjdk/library/openjdk/11.0-jdk-slim/images/sha256-446ed735fef26d5e6a87b0adde60c5347d49772af9f5469fe3a003f664dc60c4?context=explore and https://hub.docker.com/layers/adoptopenjdk/library/adoptopenjdk/11-jdk-hotspot-bionic/images/sha256-d60244febde4bec363339337d544b05ab93666e0daffca914586dac169d2ff26?context=explore - the size is nearly identical, while the "big" OpenJDK has >300 MB (https://hub.docker.com/layers/openjdk/library/openjdk/11-jdk-buster/images/sha256-23a35fb62135f527b392e55d834c646d3a2342f1d8480d4c1f316d75b7a8f9a8?context=explore)

To answer your question, just use `11`, the size affect should be unnoticeable and only around 10 MB max.

**Comment by jacobg** [comment]
@timbru31 Thanks so much, for both the explanation and of course for your hard and dedicated work at constructing these docker images and making them available.

I did notice a bit more of a different than 10 MB when the images are pulled locally:
```
timbru31/java-node            11-jre              69052857b3db        30 hours ago        382MB
timbru31/java-node            11-slim             b1ef86f73793        16 months ago       339MB
```

**Comment by timbru31** [comment]
It's a bit difficult to compare I guess, because the 11-slim tag probably has Node.js v10 or older installed. I'd suspect that Node.js gets bigger with each release, too.

Building locally I have around 30MB difference with latest Node.js v12:
```
adoptopenjdk-focal                                    latest                  d334e2efe22e        8 seconds ago       391MB
openjdk                                               latest                  757b3af84539        4 minutes ago       353MB
adoptopenjdk                                          latest                  64b2c170016d        8 minutes ago       384MB
```

Focal makes the image a bit bigger, too. I'll see if I can further trim the AdoptOpenJDK images.

**Comment by jacobg** [comment]
Gotcha. Thanks!

**Comment by timbru31** [comment]
In fact the OpenJDK images actually installs AdoptOpenJDK (https://github.com/docker-library/openjdk/blob/master/11/jre/slim-buster/Dockerfile#L42)- the Java ecosystem is so confusing right now 😂 

But, I've discovered a debianslim variant of AdoptOpenJDK, too, which is at least  bit smaller.
`adoptopenjdk-debianslim                               latest                  5cf276ded5e3        10 seconds ago      377MB`
